"""added fuel price model

Revision ID: 04264e1a1a65
Revises: 6af73b89fc56
Create Date: 2024-12-04 02:11:51.953808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04264e1a1a65'
down_revision: Union[str, None] = '6af73b89fc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_fuel_prices',
    sa.Column('fuel_type', postgresql.ENUM('diesel', 'methan', 'propane', 'ai_80', 'ai_91', 'ai_92', 'ai_95', 'ai_98', name='fueltype'), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_fuel_prices')
    # ### end Alembic commands ###
