"""added fixes 2

Revision ID: 13813cb84897
Revises: 8ef2c17d5d77
Create Date: 2024-12-16 00:43:17.970811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13813cb84897'
down_revision: Union[str, None] = '8ef2c17d5d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('private_chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'private_chats', ['private_chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'private_chat_id')
    # ### end Alembic commands ###
