"""added new model for suppor

Revision ID: 43391a046751
Revises: be632c954ee3
Create Date: 2024-12-26 02:29:45.325274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43391a046751'
down_revision: Union[str, None] = 'be632c954ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_rooms',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('support_messages', sa.Column('room_id', sa.Integer(), nullable=False))
    op.drop_constraint('support_messages_sender_fkey', 'support_messages', type_='foreignkey')
    op.drop_constraint('support_messages_answered_by_fkey', 'support_messages', type_='foreignkey')
    op.create_foreign_key(None, 'support_messages', 'support_rooms', ['room_id'], ['id'])
    op.drop_column('support_messages', 'is_answered')
    op.drop_column('support_messages', 'answered_by')
    op.drop_column('support_messages', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('support_messages', sa.Column('answered_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('is_answered', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'support_messages', type_='foreignkey')
    op.create_foreign_key('support_messages_answered_by_fkey', 'support_messages', 'operators', ['answered_by'], ['id'])
    op.create_foreign_key('support_messages_sender_fkey', 'support_messages', 'users', ['sender'], ['id'])
    op.drop_column('support_messages', 'room_id')
    op.drop_table('support_rooms')
    # ### end Alembic commands ###
