"""added sender_id for support_message

Revision ID: 520fe64b3034
Revises: 43391a046751
Create Date: 2024-12-26 16:31:43.202764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520fe64b3034'
down_revision: Union[str, None] = '43391a046751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_messages', 'sender_id')
    # ### end Alembic commands ###
