"""added fixes'


Revision ID: 605dc29d78d6
Revises: c0077391ec56
Create Date: 2025-01-02 23:26:00.848490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '605dc29d78d6'
down_revision: Union[str, None] = 'c0077391ec56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scope')
    op.add_column('web_users', sa.Column('scope', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_users', 'scope')
    op.add_column('users', sa.Column('scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
