"""added cascade to fuel price model

Revision ID: 6172a8f15b9f
Revises: ab087fd14119
Create Date: 2024-12-09 18:33:19.799447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6172a8f15b9f'
down_revision: Union[str, None] = 'ab087fd14119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_fuel_prices_place_id_fkey', 'place_fuel_prices', type_='foreignkey')
    op.create_foreign_key(None, 'place_fuel_prices', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place_fuel_prices', type_='foreignkey')
    op.create_foreign_key('place_fuel_prices_place_id_fkey', 'place_fuel_prices', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###
