"""fixed fields in verification model

Revision ID: 6af73b89fc56
Revises: bc94d17777af
Create Date: 2024-11-30 01:43:21.488521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af73b89fc56'
down_revision: Union[str, None] = 'bc94d17777af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_verification_codes', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_verification_codes', type_='unique')
    # ### end Alembic commands ###
