"""removed unique for place_ratings

Revision ID: 72f4ce25f067
Revises: e4c268842da2
Create Date: 2024-12-09 15:56:10.160673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f4ce25f067'
down_revision: Union[str, None] = 'e4c268842da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_ratings_place_id_key', 'place_ratings', type_='unique')
    op.drop_constraint('place_ratings_user_id_key', 'place_ratings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('place_ratings_user_id_key', 'place_ratings', ['user_id'])
    op.create_unique_constraint('place_ratings_place_id_key', 'place_ratings', ['place_id'])
    # ### end Alembic commands ###
