"""added place and user model

Revision ID: 815b62e39aa2
Revises: 2fe7c66d6483
Create Date: 2024-11-30 00:20:08.133973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815b62e39aa2'
down_revision: Union[str, None] = '2fe7c66d6483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('coordinates', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('yandex_map_link', sa.String(), nullable=True),
    sa.Column('has_gasoline', sa.Boolean(), nullable=False),
    sa.Column('has_ai_80', sa.Boolean(), nullable=False),
    sa.Column('has_ai_91', sa.Boolean(), nullable=False),
    sa.Column('has_ai_95', sa.Boolean(), nullable=False),
    sa.Column('has_ai_98', sa.Boolean(), nullable=False),
    sa.Column('has_diesel', sa.Boolean(), nullable=False),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('has_wc', sa.Boolean(), nullable=False),
    sa.Column('has_shop', sa.Boolean(), nullable=False),
    sa.Column('has_parking', sa.Boolean(), nullable=False),
    sa.Column('has_car_wash', sa.Boolean(), nullable=False),
    sa.Column('has_tire_service', sa.Boolean(), nullable=False),
    sa.Column('has_gas', sa.Boolean(), nullable=False),
    sa.Column('has_methane', sa.Boolean(), nullable=False),
    sa.Column('has_propane', sa.Boolean(), nullable=False),
    sa.Column('has_praying_room', sa.Boolean(), nullable=False),
    sa.Column('has_electric_charging', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('users')
    # ### end Alembic commands ###
