"""added row id to place

Revision ID: ab087fd14119
Revises: 72f4ce25f067
Create Date: 2024-12-09 18:31:42.303531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab087fd14119'
down_revision: Union[str, None] = '72f4ce25f067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('row_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'row_id')
    # ### end Alembic commands ###
