"""added fields

Revision ID: b2967943b0c1
Revises: 605dc29d78d6
Create Date: 2025-01-23 16:21:54.876369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2967943b0c1'
down_revision: Union[str, None] = '605dc29d78d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('bytes_data', sa.LargeBinary(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'bytes_data')
    # ### end Alembic commands ###
