"""added scope field to user model

Revision ID: c0077391ec56
Revises: 1fa359e7c09f
Create Date: 2025-01-02 22:34:52.479826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0077391ec56'
down_revision: Union[str, None] = '1fa359e7c09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scope', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scope')
    # ### end Alembic commands ###
