"""added chat type

Revision ID: c8cdee2aba5f
Revises: 28e191ce8d08
Create Date: 2024-12-15 20:49:08.881824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8cdee2aba5f"
down_revision: Union[str, None] = "28e191ce8d08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE chattypeenum AS ENUM ('GLOBAL', 'LOCAL')")
    op.execute("ALTER TABLE chats ADD COLUMN chat_type chattypeenum")
    # op.add_column(
    #     "chats",
    #     sa.Column(
    #         "chat_type",
    #         postgresql.ENUM("GLOBAL", "LOCAL", name="chattypeenum"),
    #         nullable=False,
    #     ),
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "chat_type")
    # ### end Alembic commands ###
