"""added unique for fields

Revision ID: e4c268842da2
Revises: ef75813c202e
Create Date: 2024-12-09 15:40:39.094050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c268842da2'
down_revision: Union[str, None] = 'ef75813c202e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place_ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'place_ratings', ['user_id'])
    op.create_unique_constraint(None, 'place_ratings', ['place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place_ratings', type_='unique')
    op.drop_constraint(None, 'place_ratings', type_='unique')
    op.alter_column('place_ratings', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
