"""changed type for rating

Revision ID: ef75813c202e
Revises: a51e26142308
Create Date: 2024-12-09 14:48:33.599315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef75813c202e"
down_revision: Union[str, None] = "a51e26142308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE place_ratings DROP COLUMN rating")
    op.execute("ALTER TABLE place_ratings ADD COLUMN rating INTEGER")
    # op.alter_column(
    #     "place_ratings",
    #     "rating",
    #     existing_type=postgresql.ENUM(
    #         "one", "two", "three", "four", "five", name="placeratingenum"
    #     ),
    #     type_=sa.Integer(),
    #     existing_nullable=False,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "place_ratings",
        "rating",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM(
            "one", "two", "three", "four", "five", name="placeratingenum"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
