"""adde fixes

Revision ID: f7fbaaafee3a
Revises: 6172a8f15b9f
Create Date: 2024-12-09 18:46:26.661584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fbaaafee3a'
down_revision: Union[str, None] = '6172a8f15b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('has_cafe', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'has_cafe')
    # ### end Alembic commands ###
